package com.example.kentekenafkomst

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import android.widget.TextView
import kotlinx.android.synthetic.main.activity_main.*


class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val knop = findViewById<Button>(R.id.StartBtn)
        knop.setOnClickListener {


            //krijg de invoer van het invoerveld "PlateText"
            var invoerTekstVeld = PlateTxt.text.toString()

            //maak van de invoer hoofdletters
            var invoer = invoerTekstVeld.toUpperCase()
            println(invoer)

            //laat het resultaat zien:
            val resultaat: TextView = findViewById(R.id.resultTextView) as TextView

            //wanneer iets gelijk is aan "Text" doe dit // anders doe "je hebt iets verkeerd getypt!"
            // de info hieronder komt van https://www.customeuropeanplates.com/german-license-plate-codes
            when{
                //officiele voertuigen
                invoer.equals("0") -> resultaat.text = "Diplomatische voertuigen"
                invoer.equals("AD") -> resultaat.text = "Amerikaanse militaire voertuigen"
                invoer.equals("BD") -> resultaat.text = "Federale voertuigen"
                invoer.equals("BG") -> resultaat.text = "Grenstroepen"
                invoer.equals("BP") -> resultaat.text = "Postwagens (BundesPost)"
                invoer.equals("BW") -> resultaat.text = "Water- en scheepsvaartautoriteit"
                invoer.equals("DB") -> resultaat.text = "Spoorwegauthoriteiten (Deutsche Bahn)"
                invoer.equals("THW") -> resultaat.text = "Burgerbescherming (Technisches Hilfswerk) "
                invoer.equals("X") -> resultaat.text = "NAVO voertuigen"
                invoer.equals("Y") -> resultaat.text = "Bundeswehr"

                //Bundesvoertuigen
                invoer.equals("BBL") -> resultaat.text = "Brandenburg (staats)voertuigen"
                invoer.equals("BWL") -> resultaat.text = "Badem-Württemberg (staats)voertuigen"
                invoer.equals("BYL") -> resultaat.text = "Beieren (staats)voertuigen"
                invoer.equals("HEL") -> resultaat.text = "Hesses (staats)voertuigen"
                invoer.equals("LSA") -> resultaat.text = "Saksen-Anhalt (staats)voertuigen"
                invoer.equals("LSN") -> resultaat.text = "Saksen (staats)voertuigen"
                invoer.equals("MVL") -> resultaat.text = "Mecklenburg-Voor-Pommeren (staats)voertuigen)"
                invoer.equals("NWR") -> resultaat.text = "Noordrijn-Westfalen (staats)voertuigen"
                invoer.equals("RPL") -> resultaat.text = "Rijnland-Palts (staats)voertuigen"
                invoer.equals("SAL") -> resultaat.text = "Saarland (staats)voertuigen"
                invoer.equals("SH") -> resultaat.text = "Sleeswijk-Holstein (staats)voertuigen"
                invoer.equals("THL") -> resultaat.text = "Thüringen (staats)voertuigen"

                //de rest           VERVARNG Thur -> thuringen, Mel en Baden door de juiste
                //A
                invoer.equals("A") -> resultaat.text = "Augsburg, Beieren"
                invoer.equals("AA") -> resultaat.text = "Aalen & Ostalbkreis, Baden-Württemberg"
                invoer.equals("AB") -> resultaat.text = "Aschaffenburg, Beieren"
                invoer.equals("ABG") -> resultaat.text = "Altenburger Land, Thüringen" 
                invoer.equals("AC") -> resultaat.text = "Aachen, Noordrijn-Westfalen"
                invoer.equals("AH") -> resultaat.text = "Ahaus, Noordrijn-Westfalen"
                invoer.equals("AIB") -> resultaat.text = "Bad Aibling, Beieren"
                invoer.equals("AIC") -> resultaat.text = "Aichach-Friedberg, Beieren"
                invoer.equals("AE") -> resultaat.text = "Auerbach, Saksen"
                invoer.equals("AK") -> resultaat.text = "Altenkirchen (Westerwald), Rijnland-Palts"
                invoer.equals("AL") -> resultaat.text = "Altena, Noordrijn-Westfalen"
                invoer.equals("ALF") -> resultaat.text = "Alfeld, Nedersaksen"
                invoer.equals("ALS") -> resultaat.text = "Alsfeld, Hessen"
                invoer.equals("ALZ") -> resultaat.text = "Alzenau, Beieren"
                invoer.equals("AM") -> resultaat.text = "Amberg, Beieren"
                invoer.equals("AN") -> resultaat.text = "Ansbach, Beieren"
                invoer.equals("ANA") -> resultaat.text = "Annaberg-Buchholz, Saksen"
                invoer.equals("ANG") -> resultaat.text = "Angermünde, Brandenburg"
                invoer.equals("ANK") -> resultaat.text = "Anklam, Mecklenburg-Voor-Pommeren" 
                invoer.equals("AÖ") -> resultaat.text = "Altötting, Beieren"
                invoer.equals("AP") -> resultaat.text = "Apolda & Weimarer Land, Thüringen" 
                invoer.equals("APD") -> resultaat.text = "Apolda, Thüringen" 
                invoer.equals("AR") -> resultaat.text = "Arnsberg, Noordrijn-Westfalen"
                invoer.equals("ARN") -> resultaat.text = "Arnstadt, Thüringen" 
                invoer.equals("ART") -> resultaat.text = "Artern, Thüringen" 
                invoer.equals("AS") -> resultaat.text = "Amberg-Sulzbach, Beieren"
                invoer.equals("ASD") -> resultaat.text = "Aschendorf, Nedersaksen"
                invoer.equals("ASL") -> resultaat.text = "Aschersleben-Staßfurter Landkreis, Saksen-Anhalt"
                invoer.equals("ASZ") -> resultaat.text = "Aue-Schwarzenberg, Saksen"
                invoer.equals("AT") -> resultaat.text = "Alten-Treptow, Mecklenburg-Voor-Pommeren" 
                invoer.equals("AU") -> resultaat.text = "Aue, Saksen"
                invoer.equals("AUR") -> resultaat.text = "Aurich, Nedersaksen"
                invoer.equals("AW") -> resultaat.text = "Ahrweiler, Rijnland-Palts"
                invoer.equals("AZ") -> resultaat.text = "Alzey-Worms, Rijnland-Palts"
                invoer.equals("AZE") -> resultaat.text = "Anhalt-Zerbst, Saksen-Anhalt"

                //B
                invoer.equals("B") -> resultaat.text = "Berlijn"
                invoer.equals("BA") -> resultaat.text = "Bamberg, Beieren"
                invoer.equals("BAD") -> resultaat.text = "Baden-Baden, Baden"
                invoer.equals("BAR") -> resultaat.text = "Barnim (Eberswelde), Brandenburg"
                invoer.equals("BB") -> resultaat.text = "Böblingen, Baden"
                invoer.equals("BBG") -> resultaat.text = "Bernburg, Saksen-Anhalt"
                invoer.equals("BC") -> resultaat.text = "Biberach, Baden"
                invoer.equals("BCH") -> resultaat.text = "Buchen, Baden"
                invoer.equals("BE") -> resultaat.text = "Bechum, Noordrijn-Westfalen"
                invoer.equals("BED") -> resultaat.text = "Brand-Erbisdorf, Saksen"
                invoer.equals("BEI") -> resultaat.text = "Beilingries, Beieren"
                invoer.equals("BEL") -> resultaat.text = "Blezig, Brandenburg"
                invoer.equals("BER") -> resultaat.text = "Bernau, Brandenburg"
                invoer.equals("BF") -> resultaat.text = "Bergsteinfurt, Noordrijn-Westfalen"
                invoer.equals("BGD") -> resultaat.text = "Berchtesgaden, Beieren"
                invoer.equals("BGL") -> resultaat.text = "Berchtesgadener Land, Beieren"
                invoer.equals("BH") -> resultaat.text = "Bühl, Baden"
                invoer.equals("BI") -> resultaat.text = "Bielefeld, Noordrijn-Westfalen"
                invoer.equals("BID") -> resultaat.text = "Biedenkopf, Hessen"
                invoer.equals("BIN") -> resultaat.text = "Bingen, Rijnland-Palts"
                invoer.equals("BIR") -> resultaat.text = "Birkenfeld, Rijnland-Palts"
                invoer.equals("BIT") -> resultaat.text = "Bitburg-Prüm, Rijnland-Palts"
                invoer.equals("BIW") -> resultaat.text = "Bischofswerda, Saksen"
                invoer.equals("BK") -> resultaat.text = "Bicknang, Baden"
                invoer.equals("BKS") -> resultaat.text = "Bernkastel, Rijnland-Palts"
                invoer.equals("BL") -> resultaat.text = "Balingen & Zollernalbkreis, Baden"
                invoer.equals("BLB") -> resultaat.text = "Bad Berleburg, Noordrijn-Westfalen"
                invoer.equals("BLK") -> resultaat.text = "Burgenlandkreis, SaksenAnhalt"
                invoer.equals("BM") -> resultaat.text = "Bergheim & Erftkreis, Noordrijn-Westfalen"
                invoer.equals("BN") -> resultaat.text = "Bonn, Noordrijn-Westfalen"
                invoer.equals("BNA") -> resultaat.text = "Borna, Saksen"
                invoer.equals("BO") -> resultaat.text = "Bochum, Noordrijn-Westfalen"
                invoer.equals("BÖ") -> resultaat.text = "Bördekreis, Saksen-Anhalt"
                invoer.equals("BOG") -> resultaat.text = "Bogen, Beieren"
                invoer.equals("BOH") -> resultaat.text = "Bocholt, Noordrijn-Westfalen"
                invoer.equals("BOR") -> resultaat.text = "Borken, Noordrijn-Westfalen"
                invoer.equals("BOT") -> resultaat.text = "Bottrop, Noordrijn-Westfalen"
                invoer.equals("BR") -> resultaat.text = "Bruchsal, Baden"
                invoer.equals("BRA") -> resultaat.text = "Brake (Unterweser) & Wesermarsch, Nedersaksen"
                invoer.equals("BRB") -> resultaat.text = "Brandenburg, Brandenburg"
                invoer.equals("BRG") -> resultaat.text = "Burg, Saksen-Anhalt"
                invoer.equals("BRI") -> resultaat.text = "Brilon, Noordrijn-Westfalen"
                invoer.equals("BRK") -> resultaat.text = "Bad Brückenau, Beieren"
                invoer.equals("BRL") -> resultaat.text = "Braunlage, Nedersaksen"
                invoer.equals("BRV") -> resultaat.text = "Bremervörde, Nedersaksen"
                invoer.equals("BS") -> resultaat.text = "Brunswick (Braunschweig), Nedersaksen"
                invoer.equals("BSB") -> resultaat.text = "Bersenbrück, Nedersaksen"
                invoer.equals("BSK") -> resultaat.text = "Beeskow, Brandenburg"
                invoer.equals("BT") -> resultaat.text = "Bayreuth, Beieren"
                invoer.equals("BTF") -> resultaat.text = "Bitterfeld, Saksen-Anhalt"
                invoer.equals("BU") -> resultaat.text = "Burgdorf, Nedersaksen"
                invoer.equals("BÜD") -> resultaat.text = "Büdingen, Hessen"
                invoer.equals("BUL") -> resultaat.text = "Burglengenfeld, Beieren"
                invoer.equals("BUR") -> resultaat.text = "Buren, Noordrijn-Westfalen"
                invoer.equals("BÜS") -> resultaat.text = "Büsingen & Konstanz, Baden-Württemberg"
                invoer.equals("BÜZ") -> resultaat.text = "Bützow, Mecklenburg-Voor-Pommeren" 
                invoer.equals("BZ") -> resultaat.text = "Bautzen, Saksen"
                invoer.equals("BZA") -> resultaat.text = "Bergzabern, Rijnland-Palts"

                //C
                invoer.equals("C") -> resultaat.text = "Chemnitz, Saksen"
                invoer.equals("CA") -> resultaat.text = "Calau, Brandenburg"
                invoer.equals("CAS") -> resultaat.text = "Castrop-Rauxel, Noordrijn-Westfalen"
                invoer.equals("CB") -> resultaat.text = "Cottbus, Brandenburg"
                invoer.equals("CE") -> resultaat.text = "Celle, Nedersaksen"
                invoer.equals("CHA") -> resultaat.text = "Cham, Beieren"
                invoer.equals("CHL") -> resultaat.text = "Chemnitzer Land, Kreis Glochau, Saksen"
                invoer.equals("CLP") -> resultaat.text = "Cloppenburg, Nedersaksen"
                invoer.equals("CLZ") -> resultaat.text = "Clausthal-Zellerfeld, Nedersaksen"
                invoer.equals("CO") -> resultaat.text = "Coburg, Beieren"
                invoer.equals("COC") -> resultaat.text = "Cochem-Zell, Rijnland-Palts"
                invoer.equals("COE") -> resultaat.text = "Coesfeld, Noordrijn-Westfalen"
                invoer.equals("CR") -> resultaat.text = "Crailsheim, Baden"
                invoer.equals("CT") -> resultaat.text = "Cottbus, Saksen"
                invoer.equals("CUX") -> resultaat.text = "Cuxhaven, Nedersaksen"
                invoer.equals("CW") -> resultaat.text = "Calw, Baden"

                //D
                invoer.equals("D") -> resultaat.text = "Düsseldorf, Noordrijn-Westfalen"
                invoer.equals("DA") -> resultaat.text = "Darmstadt & Darmstadt-Dieburg, Hessen"
                invoer.equals("DAH") -> resultaat.text = "Dachau, Beieren"
                invoer.equals("DAN") -> resultaat.text = "Lüchow-Dannenberg, Nedersaksen"
                invoer.equals("DAU") -> resultaat.text = "Daun, Rijnland-Palts"
                invoer.equals("DBR") -> resultaat.text = "Bad Doberan, Mecklenburg-Voor-Pommeren" 
                invoer.equals("DD") -> resultaat.text = "Dresden"
                invoer.equals("DE") -> resultaat.text = "Dessau, Nedersaksen"
                invoer.equals("DEG") -> resultaat.text = "Deggendorf, Beieren"
                invoer.equals("DEL") -> resultaat.text = "Delmenhorst, Nedersaksen"
                invoer.equals("DG") -> resultaat.text = "Donaueschingen, Baden"
                invoer.equals("DGF") -> resultaat.text = "Dingolfling-Landau, Beieren"
                invoer.equals("DH") -> resultaat.text = "Diepholz, Nedersaksen"
                invoer.equals("DI") -> resultaat.text = "Dieburg, Hessen"
                invoer.equals("DIL") -> resultaat.text = "Dillenburg, Hessen"
                invoer.equals("DIN") -> resultaat.text = "Dinslaken, Noordrijn-Westfalen"
                invoer.equals("DIZ") -> resultaat.text = "Diez, Rijnland-Palts"
                invoer.equals("DKB") -> resultaat.text = "Dinkelsbühl, Beieren"
                invoer.equals("DL") -> resultaat.text = "Döbeln, Saksen"
                invoer.equals("DLG") -> resultaat.text = "Dillengen an der Donau, Beieren"
                invoer.equals("DM") -> resultaat.text = "Demmin, Mecklenburg-Voor-Pommeren" 
                invoer.equals("DN") -> resultaat.text = "Düren, Noordrijn-Westfalen"
                invoer.equals("DO") -> resultaat.text = "Dortmund, Noordrijn-Westfalen"
                invoer.equals("DON") -> resultaat.text = "Donau-Ries, Beieren"
                invoer.equals("DS") -> resultaat.text = "Donaueschingen, Baden"
                invoer.equals("DT") -> resultaat.text = "Detmold & Lippe, Noordrijn-Westfalen"
                invoer.equals("DU") -> resultaat.text = "Duisburg, Noordrijn-Westfalen"
                invoer.equals("DUD") -> resultaat.text = "Duderstadt, Nedersaksen"
                invoer.equals("DÜW") -> resultaat.text = "Bad Dürkheim & Weinstraße, Rijnland-Palts"
                invoer.equals("DW") -> resultaat.text = "Dippoldiswalde & Weißeritzkreis, Saksen"
                invoer.equals("DZ") -> resultaat.text = "Delitzsch, Saksen"

                //E
                invoer.equals("E") -> resultaat.text = "Essen, Noordrijn-Westfalen"
                invoer.equals("EA") -> resultaat.text = "Eisenach, Thüringen" 
                invoer.equals("EB") -> resultaat.text = "Eilenburg, Saksen"
                invoer.equals("EBE") -> resultaat.text = "Ebersberg, Beieren"
                invoer.equals("EBS") -> resultaat.text = "Ebermannstadt, Beieren"
                invoer.equals("ECK") -> resultaat.text = "Eckernförde, Sleeswijk-Holstein"
                invoer.equals("ED") -> resultaat.text = "Erding, Beieren"
                invoer.equals("EE") -> resultaat.text = "Elbe-Elster, Brandenburg"
                invoer.equals("EF") -> resultaat.text = "Erfurt, Thüringen" 
                invoer.equals("EG") -> resultaat.text = "Eggenfelden, Beieren"
                invoer.equals("EH") -> resultaat.text = "Eisenhüttenstadt, Brandenburg"
                invoer.equals("EHI") -> resultaat.text = "Ehingen, Baden"
                invoer.equals("EI") -> resultaat.text = "Eichstätt, Beieren"
                invoer.equals("EIC") -> resultaat.text = "Eichsfeld, Thüringen" 
                invoer.equals("EIH") -> resultaat.text = "Eichstätt, Beieren"
                invoer.equals("EIL") -> resultaat.text = "Eisleben, Saksen-Anhalt"
                invoer.equals("EIN") -> resultaat.text = "Einbeck, Nedersaksen"
                invoer.equals("EIS") -> resultaat.text = "Eisenberg, Thüringen? (Deelstaat onbekend, aanname gedaan)"
                invoer.equals("EL") -> resultaat.text = "Emsland, Nedersaksen"
                invoer.equals("EM") -> resultaat.text = "Emmendingen, Baden"
                invoer.equals("EMD") -> resultaat.text = "Emden, Nedersaksen"
                invoer.equals("EMS") -> resultaat.text = "Bad Ems & Rhein-Lahn-Kreis, Rijnland-Palts"
                invoer.equals("EN") -> resultaat.text = "Ennepe-Ruhr-Kreis, Noordrijn-Westfalen"
                invoer.equals("ER ") -> resultaat.text = "Erlangen, Beieren"
                invoer.equals("ERB") -> resultaat.text = "Erbach & Oldenwaldkreis, Hessen"
                invoer.equals("ERH") -> resultaat.text = "Erlangen-Höchstadt, Beieren"
                invoer.equals("ERK") -> resultaat.text = "Erkelenz, Noordrijn-Westfalen"
                invoer.equals("ES") -> resultaat.text = "Esslingen, Baden"
                invoer.equals("ESA") -> resultaat.text = "Eisenach, Thüringen" 
                invoer.equals("ESB") -> resultaat.text = "Eschenbach, Beieren"
                invoer.equals("ESW") -> resultaat.text = "Eschwege & Werra-Meißner-Kreis, Hessen"
                invoer.equals("EU") -> resultaat.text = "Euskirchen, Noordrijn-Westfalen"
                invoer.equals("EUT") -> resultaat.text = "Eutin, Sleeswijk-Holstein"
                invoer.equals("EW") -> resultaat.text = "Eberswalde, Brandenburg"

                //F
                invoer.equals("F") -> resultaat.text = "Frankfurt am Main, Hessen"
                invoer.equals("FAL") -> resultaat.text = "Fallingbostel, Noordrijn-Westfalen"
                invoer.equals("FB") -> resultaat.text = "Friedberg (Hessen) & Wetteraukreis, Hessen"
                invoer.equals("FD") -> resultaat.text = "Fulda, Hessen"
                invoer.equals("FDB") -> resultaat.text = "Friedberg bei Augsburg, Beieren"
                invoer.equals("FF") -> resultaat.text = "Frankfurt-an-der-Oder, Brandenburg"
                invoer.equals("FFB") -> resultaat.text = "Fürstenfeldbruck, Beieren"
                invoer.equals("FG") -> resultaat.text = "Freiberg, Saksen"
                invoer.equals("FH") -> resultaat.text = "Frankfurt am Main/Höchst, Hessen"
                invoer.equals("FI") -> resultaat.text = "Finsterwalde, Brandenburg"
                invoer.equals("FKB") -> resultaat.text = "Frankenberg, Hessen"
                invoer.equals("FL") -> resultaat.text = "Flensburg, Sleeswijk-Holstein"
                invoer.equals("FLÖ") -> resultaat.text = "Flöha, Saksen"
                invoer.equals("FN") -> resultaat.text = "Friedrichshafen & Bodenseekreis, Baden"
                invoer.equals("FO") -> resultaat.text = "Forchheim, Beieren"
                invoer.equals("FOR") -> resultaat.text = "Forst, Brandenburg"
                invoer.equals("FR") -> resultaat.text = "Freiburg im Breisgau & Breisgau-Hochschwarzwald, Baden"
                invoer.equals("FRG") -> resultaat.text = "Freyung-Grafenau, Beieren"
                invoer.equals("FRI") -> resultaat.text = "Friesland, Nedersaksen"
                invoer.equals("FRW") -> resultaat.text = "Bad Freienwalde, Brandenburg"
                invoer.equals("FS") -> resultaat.text = "Freising, Beieren"
                invoer.equals("FT") -> resultaat.text = "Frankenthal (Pfalz), Rijnland-Palts"
                invoer.equals("FTL") -> resultaat.text = "Freital, Saksen"
                invoer.equals("FÜ") -> resultaat.text = "Fürth, Beieren"
                invoer.equals("FÜS") -> resultaat.text = "Füssen, Beieren"
                invoer.equals("FW") -> resultaat.text = "Fürstenwalde, Brandenburg"
                invoer.equals("FZ") -> resultaat.text = "Fritzlar, Hessen"

                //G
                invoer.equals("G") -> resultaat.text = "Gera, Thüringen" 
                invoer.equals("GA") -> resultaat.text = "Gardelegen, Saksen-Anhalt"
                invoer.equals("GAN") -> resultaat.text = "Bad Gandersheim, Nedersaksen"
                invoer.equals("GAP") -> resultaat.text = "Garmisch-Partenkirchen, Beieren"
                invoer.equals("GC") -> resultaat.text = "Glauchau & Chemnitzer Land, Saksen"
                invoer.equals("GD") -> resultaat.text = "Gmünd, Baden-Württemberg"
                invoer.equals("GDB") -> resultaat.text = "Gadesbusch, Mecklenburg-Voor-Pommeren" 
                invoer.equals("GE") -> resultaat.text = "Gelsenkirchen, Noordrijn-Westfalen"
                invoer.equals("GEL") -> resultaat.text = "Geldern, Noordrijn-Westfalen"
                invoer.equals("GEM") -> resultaat.text = "Gemünden, Beieren"
                invoer.equals("GEO") -> resultaat.text = "Gerolzhofen, Beieren"
                invoer.equals("GER") -> resultaat.text = "Germersheim, Rijnland-Palts"
                invoer.equals("GF") -> resultaat.text = "Gifhorn, Nedersaksen"
                invoer.equals("GG") -> resultaat.text = "Groß-Gerau, Hessen"
                invoer.equals("GHA") -> resultaat.text = "Geithain, Saksen"
                invoer.equals("GHC") -> resultaat.text = "Gräfenhainichen, Saksen-Anhalt"
                invoer.equals("GI") -> resultaat.text = "Gießen, Hessen"
                invoer.equals("GK") -> resultaat.text = "Geilenkirchen, Noordrijn-Westfalen"
                invoer.equals("GL") -> resultaat.text = "Bergisch-Gladbach & Rheinisch-Bergischer Kreis, Noordrijn-Westfalen"
                invoer.equals("GLA") -> resultaat.text = "Gladbeck, Noordrijn-Westfalen"
                invoer.equals("GM") -> resultaat.text = "Gemmersbach & Oberbergischer Kreis, Noordrijn-Westfalen"
                invoer.equals("GMN") -> resultaat.text = "Grimmen, Mecklenburg-Voor-Pommeren" 
                invoer.equals("GN") -> resultaat.text = "Gelnhausen, Hessen"
                invoer.equals("GNT") -> resultaat.text = "Genthin, Saksen-Anhalt"
                invoer.equals("GÖ") -> resultaat.text = "Göttingen, Nedersaksen"
                invoer.equals("GOA") -> resultaat.text = "St Goar, Rijnland-Palts"
                invoer.equals("GOH") -> resultaat.text = "St Goarhausen, Rijnland-Palts"
                invoer.equals("GP") -> resultaat.text = "Göppingen, Baden-Württemberg"
                invoer.equals("GR") -> resultaat.text = "Görlitz, Saksen"
                invoer.equals("GRA") -> resultaat.text = "Grafenau, Beieren"
                invoer.equals("GRH") -> resultaat.text = "Grossenheim, Saksen? (Deelstaat onbekend, aanname gedaan)"
                invoer.equals("GRI") -> resultaat.text = "Griesbach, Beieren"
                invoer.equals("GRM") -> resultaat.text = "Grimma, Saksen"
                invoer.equals("GRS") -> resultaat.text = "Gransee, Brandenburg"
                invoer.equals("GRZ") -> resultaat.text = "Greiz, Thüringen" 
                invoer.equals("GS") -> resultaat.text = "Goslar, Nedersaksen"
                invoer.equals("GT") -> resultaat.text = "Gütersloh, Noordrijn-Westfalen"
                invoer.equals("GTH") -> resultaat.text = "Gotha, Thüringen" 
                invoer.equals("GÜ") -> resultaat.text = "Güstrow, Mecklenburg-Voor-Pommeren" 
                invoer.equals("GUB") -> resultaat.text = "Guben, Brandenburg"
                invoer.equals("GUN") -> resultaat.text = "Gunzenhausen, Beieren"
                invoer.equals("GV") -> resultaat.text = "Gravenbroich, Noordrijn-Westfalen"
                invoer.equals("GVM") -> resultaat.text = "Grevesmühlen, Mecklenburg-Voor-Pommeren" 
                invoer.equals("GW") -> resultaat.text = "Greifswald Land, Mecklenburg-Voor-Pommeren" 
                invoer.equals("GZ") -> resultaat.text = "Günzburg, Beieren"

                //H
                invoer.equals("H") -> resultaat.text = "Hanover (Hannover), Nedersaksen"
                invoer.equals("HA") -> resultaat.text = "Hagen, Noordrijn-Westfalen"
                invoer.equals("HAB") -> resultaat.text = "Hammelburg, Beieren"
                invoer.equals("HAL") -> resultaat.text = "Halle, Saksen-Anhalt"
                invoer.equals("HAM") -> resultaat.text = "Hamm, Noordrijn-Westfalen"
                invoer.equals("HAS") -> resultaat.text = "Haßberge, Beieren"
                invoer.equals("HB") -> resultaat.text = "Hansestadt Bremen"
                invoer.equals("HBN") -> resultaat.text = "Hildburghausen, Thüringen" 
                invoer.equals("HBS") -> resultaat.text = "Halberstadt, Saksen-Anhalt"
                invoer.equals("HC") -> resultaat.text = "Hainichen, Saksen"
                invoer.equals("HCH") -> resultaat.text = "Heichingen, Baden"
                invoer.equals("HD") -> resultaat.text = "Heidelberg & Rhein-Neckar-Kreis, Baden"
                invoer.equals("HDH") -> resultaat.text = "Heidenheim, Baden"
                invoer.equals("HE") -> resultaat.text = "Helmstedt, Nedersaksen"
                invoer.equals("HEB") -> resultaat.text = "Hersbruck, Beieren"
                invoer.equals("HEF") -> resultaat.text = "Hersfeld-Rotenburg, Hessen"
                invoer.equals("HEI") -> resultaat.text = "Heide & Ditmarschen, Sleeswijk-Holstein"
                invoer.equals("HER") -> resultaat.text = "Herne, Noordrijn-Westfalen"
                invoer.equals("HET") -> resultaat.text = "Hettstedt, Saksen-Anhalt"
                invoer.equals("HF") -> resultaat.text = "Herford, Noordrijn-Westfalen"
                invoer.equals("HG") -> resultaat.text = "Bad Homburg vor der Höhe & Hochtaunuskreis, Hessen"
                invoer.equals("HGN") -> resultaat.text = "Hagenow, Mecklenburg-Voor-Pommeren" 
                invoer.equals("HGW") -> resultaat.text = "Hansestadt Greifswald, Mecklenburg-Voor-Pommeren" 
                invoer.equals("HH") -> resultaat.text = "Hansestadt Hamburg"
                invoer.equals("HHM") -> resultaat.text = "Hohenmölsen, Saksen-Anhalt"
                invoer.equals("HI") -> resultaat.text = "Hildesheim, Nedersaksen"
                invoer.equals("HIG") -> resultaat.text = "Heiligenstadt, Thüringen" 
                invoer.equals("HIP") -> resultaat.text = "Hilpoltstein, Beieren"
                invoer.equals("HK") -> resultaat.text = "Hildekreis, Nedersaksen"
                invoer.equals("HL") -> resultaat.text = "Hansestadt Lübeck, Sleeswijk-Holstein"
                invoer.equals("HM") -> resultaat.text = "Hamelen(Hameln)-Pyrmont, Nedersaksen"
                invoer.equals("HMU") -> resultaat.text = "Hanoversch Münden, Nedersaksen"
                invoer.equals("HN") -> resultaat.text = "Heilbronn, Baden"
                invoer.equals("HO") -> resultaat.text = "Hof, Beieren"
                invoer.equals("HOG") -> resultaat.text = "Hofgeismar, Hessen"
                invoer.equals("HOH") -> resultaat.text = "Hofheim, Beieren"
                invoer.equals("HOL") -> resultaat.text = "Holzminden, Nedersaksen"
                invoer.equals("HOM") -> resultaat.text = "Homburg & Saar-Pfalz-Kreis, Saarland"
                invoer.equals("HOR") -> resultaat.text = "Horb, Baden"
                invoer.equals("HÖS") -> resultaat.text = "Höchstadt, Beieren"
                invoer.equals("HOT") -> resultaat.text = "Hohenstein-Ernstthal, Saksen"
                invoer.equals("HP") -> resultaat.text = "Heppenheim an der Bergstraße & Bergstraße, Hessen"
                invoer.equals("HR") -> resultaat.text = "Homberg & Schwalm-Eder-Kreis, Hessen"
                invoer.equals("HRO") -> resultaat.text = "Hansestadt Rostock, Mecklenburg-Voor-Pommeren" 
                invoer.equals("HS") -> resultaat.text = "Heinsberg, Noordrijn-Westfalen"
                invoer.equals("HSK") -> resultaat.text = "Hochsauerlandkreis, Noordrijn-Westfalen"
                invoer.equals("HST") -> resultaat.text = "Hansestadt Stralsund, Mecklenburg-Voor-Pommeren" 
                invoer.equals("HU") -> resultaat.text = "Hanau & Main-Kinzig-Kreis, Hessen"
                invoer.equals("HÜN") -> resultaat.text = "Hünfeld, Sleeswijk-Holstein"
                invoer.equals("HUS") -> resultaat.text = "Husum, Sleeswijk-Holstein"
                invoer.equals("HV") -> resultaat.text = "Havelberg, Saksen-Anhalt"
                invoer.equals("HVL") -> resultaat.text = "Havelland, Brandenburg"
                invoer.equals("HW") -> resultaat.text = "Halle Westfalen, Noordrijn-Westfalen"
                invoer.equals("HWI") -> resultaat.text = "Hansestadt Wismar, Mecklenburg-Voor-Pommeren" 
                invoer.equals("HX") -> resultaat.text = "Höxter, Noordrijn-Westfalen" 
                invoer.equals("HY") -> resultaat.text = "Hoyerswerda, Saksen"
                invoer.equals("HZ") -> resultaat.text = "Herzberg, Brandenburg"

                //I
                invoer.equals("IGB") -> resultaat.text = "Stadt St Ingbert & Saar-Pfalz-Kreis, Saarland"
                invoer.equals("IK") -> resultaat.text = "Ilm-Kreis, Thüringen" 
                invoer.equals("IL") -> resultaat.text = "Ilmenau, Thüringen" 
                invoer.equals("ILL") -> resultaat.text = "Illertissen, Beieren"
                invoer.equals("IN") -> resultaat.text = "Ingolstadt, Beieren"
                invoer.equals("IS") -> resultaat.text = "Iserlohn, Noordrijn-Westfalen"
                invoer.equals("IZ") -> resultaat.text = "Itzehoe & Steinburg, Sleeswijk-Holstein"

                //J
                invoer.equals("J") -> resultaat.text = "Jena, Thüringen" 
                invoer.equals("JB") -> resultaat.text = "Jüterbog, Brandenburg"
                invoer.equals("JE") -> resultaat.text = "Jessen, Saksen-Anhalt"
                invoer.equals("JEV") -> resultaat.text = "Jever, Nedersaksen"
                invoer.equals("JL") -> resultaat.text = "Jelichower Land, Saksen-Anhalt"
                invoer.equals("JÜL") -> resultaat.text = "Jülich, Noordrijn-Westfalen"

                //K
                invoer.equals("K") -> resultaat.text = "Keulen (Köln), Noordrijn-Westfalen"
                invoer.equals("KA") -> resultaat.text = "Karlsruhe, Baden"
                invoer.equals("KAR") -> resultaat.text = "Karlstadt, Beieren"
                invoer.equals("KB") -> resultaat.text = "Korbach & Waldeck-Frankenberg, Hessen"
                invoer.equals("KC") -> resultaat.text = "Kronach, Beieren"
                invoer.equals("KE") -> resultaat.text = "Kempten (Allgäu), Beieren"
                invoer.equals("KEH") -> resultaat.text = "Kelheim, Beieren"
                invoer.equals("KEM") -> resultaat.text = "Kemnath, Beieren"
                invoer.equals("KF") -> resultaat.text = "Kaufbeuren, Beieren"
                invoer.equals("KG") -> resultaat.text = "Bad Kissingen, Beieren"
                invoer.equals("KH") -> resultaat.text = "Bad Kreuznach, Rijnland-Palts"
                invoer.equals("KI") -> resultaat.text = "Kiel, Sleesweg-Holstein"
                invoer.equals("KIB") -> resultaat.text = "Kirchheimbolanden & Donnersbergkreis, Rijnland-Palts"
                invoer.equals("KK") -> resultaat.text = "Kempen-Krefeld, Noordrijn-Westfalen" 
                invoer.equals("KL") -> resultaat.text = "Kaiserslauten, Rijnland-Palts"
                invoer.equals("KLE") -> resultaat.text = "Kleef (Kleve), Noordrijn-Westfalen"
                invoer.equals("KLT") -> resultaat.text = "Klingental, Saksen"
                invoer.equals("KLZ") -> resultaat.text = "Klötze, Saksen-Anhalt"
                invoer.equals("KM") -> resultaat.text = "Kamenz, Saksen"
                invoer.equals("KN") -> resultaat.text = "Konstanz, Baden"
                invoer.equals("KM") -> resultaat.text = "Kamenz, Saksen"
                invoer.equals("KO") -> resultaat.text = "Koblenz, Rijnland-Palts"
                invoer.equals("KÖN") -> resultaat.text = "Kötzting, Beieren"
                invoer.equals("KÖT") -> resultaat.text = "Köthen, Saksen-Anhalt"
                invoer.equals("KOZ") -> resultaat.text = "Kotzting, Beieren ??"
                invoer.equals("KR") -> resultaat.text = "Krefeld, Noordrijn-Westfalen" 
                invoer.equals("KRU") -> resultaat.text = "Krumbach, Beieren"
                invoer.equals("KS") -> resultaat.text = "Kassel, Hessen"
                invoer.equals("KT") -> resultaat.text = "Kitzingen, Beieren"
                invoer.equals("KU") -> resultaat.text = "Kulmbach, Beieren"
                invoer.equals("KÜN") -> resultaat.text = "Küzelsau & Hohenlohekreis, Baden-Württemberg"
                invoer.equals("KUS") -> resultaat.text = "Kusel, Rijnland-Palts"
                invoer.equals("KW") -> resultaat.text = "Königs-Wusterhausen, Brandenburg"
                invoer.equals("KY") -> resultaat.text = "Kyritz, Brandenburg"
                invoer.equals("KYF") -> resultaat.text = "Kyffhäuserkreis, Thüringen" 

                //L
                invoer.equals("L") -> resultaat.text = "Leipzig, Saksen"
                invoer.equals("LA") -> resultaat.text = "Landshut, Beieren"
                invoer.equals("LAN") -> resultaat.text = "Landau Isar, Beieren"
                invoer.equals("LAT") -> resultaat.text = "Lauterbach, Hessen"
                invoer.equals("LAU") -> resultaat.text = "Lauf an der Pegnitz & Nürnberger Land, Beieren"
                invoer.equals("LB") -> resultaat.text = "Ludwigsburg, Baden"
                invoer.equals("LBS") -> resultaat.text = "Lobenstein, Thüringen" 
                invoer.equals("LBZ") -> resultaat.text = "Lübz, Mecklenburg-Voor-Pommeren" 
                invoer.equals("LC") -> resultaat.text = "Luckau, Brandenburg"
                invoer.equals("LD") -> resultaat.text = "Landau in der Pfalz, Rijnland-Palts"
                invoer.equals("LDK") -> resultaat.text = "Lahn-Dill-Kreis, Hessen"
                invoer.equals("LDS") -> resultaat.text = "Landkreis Dahme-Spreewald, Brandenburg"
                invoer.equals("LE") -> resultaat.text = "Lemgo, Noordrijn-Westfalen" 
                invoer.equals("LEO") -> resultaat.text = "Leonberg, Baden"
                invoer.equals("LER") -> resultaat.text = "Leer (Ostfriesland), Nedersaksen"
                invoer.equals("LEV") -> resultaat.text = "Leverkusen, Noordrijn-Westfalen" 
                invoer.equals("LF") -> resultaat.text = "Laufen, Beieren"
                invoer.equals("LG") -> resultaat.text = "Lüneburg, Nedersaksen"
                invoer.equals("LH") -> resultaat.text = "Lüdunghausen, Noordrijn-Westfalen" 
                invoer.equals("LI") -> resultaat.text = "Lindau (Bodensee), Beieren"
                invoer.equals("LIB") -> resultaat.text = "Bad Liebenwerda, Brandenburg"
                invoer.equals("LIF") -> resultaat.text = "Lichtenfels, Beieren"
                invoer.equals("LIN") -> resultaat.text = "Lingen, Nedersaksen"
                invoer.equals("LIP") -> resultaat.text = "Lippe, Noordrijn-Westfalen" 
                invoer.equals("LK") -> resultaat.text = "Lübbecke, Noordrijn-Westfalen" 
                invoer.equals("LL") -> resultaat.text = "Landsberg am Lech, Beieren"
                invoer.equals("LM") -> resultaat.text = "Limburg-Weilburg, Hessen"
                invoer.equals("LN") -> resultaat.text = "Lübben, Brandenburg"
                invoer.equals("LÖ") -> resultaat.text = "Lörrach, Baden-Württemberg"
                invoer.equals("LÖB") -> resultaat.text = "Löbau, Saksen"
                invoer.equals("LOH") -> resultaat.text = "Lohr am Main, Beieren"
                invoer.equals("LOS") -> resultaat.text = "Landkreis Oder-Spree, Brandenburg"
                invoer.equals("LP") -> resultaat.text = "Lippstadt, Noordrijn-Westfalen" 
                invoer.equals("LR") -> resultaat.text = "Lahr, Baden"
                invoer.equals("LS") -> resultaat.text = "Lüdenscheid, Noordrijn-Westfalen" 
                invoer.equals("LSA") -> resultaat.text = "Saksen-Anhalt (staats)voertuigen"
                invoer.equals("LSN") -> resultaat.text = "Saksen (staats)voertuigen"
                invoer.equals("LSZ") -> resultaat.text = "Bad Langensalza, Thüringen" 
                invoer.equals("LU") -> resultaat.text = "Ludwigshafen am Rhein, Rijnland-Palts"
                invoer.equals("LÜD") -> resultaat.text = "Lüdenscheid, Noordrijn-Westfalen" 
                invoer.equals("LUK") -> resultaat.text = "Luckenwalde, Brandenburg"
                invoer.equals("LÜN") -> resultaat.text = "Lünen, Noordrijn-Westfalen" 
                invoer.equals("LWL") -> resultaat.text = "Ludwigslust, Mecklenburg-Voor-Pommeren" 

                //M
                invoer.equals("M") -> resultaat.text = "München, Beieren"
                invoer.equals("MA") -> resultaat.text = "Mannheim, Baden"
                invoer.equals("MAB") -> resultaat.text = "Marienberg, Saksen"
                invoer.equals("MAI") -> resultaat.text = "Mainburg, Beieren"
                invoer.equals("MAK") -> resultaat.text = "Marktredwitz, Beieren"
                invoer.equals("MAL") -> resultaat.text = "Mallersdorf, Beieren"
                invoer.equals("MAR") -> resultaat.text = "Marktheiedenfeld, Beieren"
                invoer.equals("MB") -> resultaat.text = "Miesbach, Beieren"
                invoer.equals("MC") -> resultaat.text = "Malchin, Mecklenburg-Voor-Pommeren" 
                invoer.equals("MD") -> resultaat.text = "Magdeburg, Saksen-Anhalt"
                invoer.equals("ME") -> resultaat.text = "Mettmann, Noordrijn-Westfalen" 
                invoer.equals("MED") -> resultaat.text = "Meldorf, Sleeswijk-Holstein"
                invoer.equals("MEG") -> resultaat.text = "Melsungen, Hessen"
                invoer.equals("MEI") -> resultaat.text = "Meissen, Saksen"
                invoer.equals("MEK") -> resultaat.text = "Mittlerer Erzgebirgskreis, Saksen"
                invoer.equals("MEL") -> resultaat.text = "Melle, Nedersaksen"
                invoer.equals("MEP") -> resultaat.text = "Meppen, Nedersaksen"
                invoer.equals("MER") -> resultaat.text = "Merseburg, Saksen-Anhalt"
                invoer.equals("MES") -> resultaat.text = "Meschede, Noordrijn-Westfalen" 
                invoer.equals("MET") -> resultaat.text = "Mellrichstadt, Beieren"
                invoer.equals("MG") -> resultaat.text = "Mönchengladbach, Noordrijn-Westfalen" 
                invoer.equals("MGH") -> resultaat.text = "Bad Mergentheim, Baden"
                invoer.equals("MGN") -> resultaat.text = "Meiningen, Thüringen" 
                invoer.equals("MH") -> resultaat.text = "Mülheim an der Ruhr, Noordrijn-Westfalen" 
                invoer.equals("MHL") -> resultaat.text = "Mühlhausen, Thüringen" 
                invoer.equals("MI") -> resultaat.text = "Minden-Lübbecke, Noordrijn-Westfalen" 
                invoer.equals("MIL") -> resultaat.text = "Miltenberg, Beieren"
                invoer.equals("MK") -> resultaat.text = "Märkischer Kreis, Noordrijn-Westfalen" 
                invoer.equals("MKK") -> resultaat.text = "Main-Kinzig-Kreis, Hessen"
                invoer.equals("ML") -> resultaat.text = "Mansfelder Land, Saksen-Anhalt"
                invoer.equals("MM") -> resultaat.text = "Memmingen, Beieren"
                invoer.equals("MN") -> resultaat.text = "Mindelheim & Unterallgäu, Beieren"
                invoer.equals("MO") -> resultaat.text = "Moers, Noordrijn-Westfalen" 
                invoer.equals("MOD") -> resultaat.text = "Marktoberdorf, Beieren"
                invoer.equals("MOL") -> resultaat.text = "Märkisch-Oderland, Brandenburg"
                invoer.equals("MON") -> resultaat.text = "Monschau, Noordrijn-Westfalen" 
                invoer.equals("MOS") -> resultaat.text = "Mosbach & Neckar-Odenwald-Kreis, Baden"
                invoer.equals("MQ") -> resultaat.text = "Merseburg-Quefurt, Saksen-Anhalt"
                invoer.equals("MR") -> resultaat.text = "Marburg-Biedenkopf, Hessen"
                invoer.equals("MS") -> resultaat.text = "Münster, Noordrijn-Westfalen" 
                invoer.equals("MSP") -> resultaat.text = "Main-Spessart-Kreis, Beieren"
                invoer.equals("MST") -> resultaat.text = "Mecklenburg-Strelitz, Mecklenburg-Voor-Pommeren" 
                invoer.equals("MT") -> resultaat.text = "Montabaur, Rijnland-Palts"
                invoer.equals("MTK") -> resultaat.text = "Main-Taunus-Kreis, Hessen"
                invoer.equals("MTL") -> resultaat.text = "Muldentalkreis, Saksen"
                invoer.equals("MÜ") -> resultaat.text = "Mühldorf am Inn, Beieren"
                invoer.equals("MÜB") -> resultaat.text = "Münchberg, Beieren"
                invoer.equals("MÜL") -> resultaat.text = "Müllheim, Baden-Württemberg"
                invoer.equals("MÜN") -> resultaat.text = "Münsingen, Baden-Württemberg"
                invoer.equals("MÜR") -> resultaat.text = "Müritz, Mecklenburg-Voor-Pommeren" 
                invoer.equals("MVL") -> resultaat.text = "Mecklenburg-Voor-Pommeren (staats)voertuigen"
                invoer.equals("MW") -> resultaat.text = "Mittweida, Saksen"
                invoer.equals("MY") -> resultaat.text = "Mayen, Rijnland-Palts"
                invoer.equals("MYK") -> resultaat.text = "Mayen-Koblenz, Rijnland-Palts"
                invoer.equals("MZ") -> resultaat.text = "Mainz & Mainz-Bingen, Rijnland-Palts"
                invoer.equals("MZG") -> resultaat.text = "Merzig-Wadern, Saarland"

                //N
                invoer.equals("N") -> resultaat.text = "Neurenberg (Nürnberg), Beieren"
                invoer.equals("NAB") -> resultaat.text = "Nabburg, Beieren"
                invoer.equals("NAI") -> resultaat.text = "Naila, Beieren"
                invoer.equals("NAU") -> resultaat.text = "Nauen, Brandenburg"
                invoer.equals("NB") -> resultaat.text = "Neubrandenburg, Mecklenburg-Voor-Pommeren" 
                invoer.equals("ND") -> resultaat.text = "Neuberg an der Donau & Neuberg-Schrobenhausen, Beieren"
                invoer.equals("NDH") -> resultaat.text = "Nordhausen, Thüringen" 
                invoer.equals("NE") -> resultaat.text = "Neuss, Noordrijn-Westfalen" 
                invoer.equals("NEA") -> resultaat.text = "Neustadt an der Aisch & Bad Windsheim, Beieren"
                invoer.equals("NEB") -> resultaat.text = "Nebra, Saksen-Anhalt"
                invoer.equals("NEC") -> resultaat.text = "Neustadt Coburg, Beieren"
                invoer.equals("NEN") -> resultaat.text = "Neunburg, Beieren"
                invoer.equals("NES") -> resultaat.text = "Bad Neustadt an der Saale & Rhön-Grabfeld, Beieren"
                invoer.equals("NEU") -> resultaat.text = "Neustadt Schwarzwald, Baden"
                invoer.equals("NEW") -> resultaat.text = "Neuschadt am der Waldnaab, Beieren"
                invoer.equals("NF") -> resultaat.text = "Nordfriesland, Sleeswijk-Holstein"
                invoer.equals("NH") -> resultaat.text = "Neuhaus an der Rennweg, Thüringen" 
                invoer.equals("NI") -> resultaat.text = "Nienbierg (Weser), Nedersaksen"
                invoer.equals("NIB") -> resultaat.text = "Niebüll, Sleeswijk-Holstein"
                invoer.equals("NK") -> resultaat.text = "Neunkirchen/Saar, Saarland"
                invoer.equals("NL") -> resultaat.text = "Nedersaksen (staats)voertuigen"
                invoer.equals("NM") -> resultaat.text = "Neumarkt in der Oberpfalz, Beieren"
                invoer.equals("NMB") -> resultaat.text = "Naumberg, Sleeswijk-Holstein"
                invoer.equals("NMS") -> resultaat.text = "Neumünster, Sleeswijk-Holstein"
                invoer.equals("NÖ") -> resultaat.text = "Nördlingen, Beieren"
                invoer.equals("NOH") -> resultaat.text = "Nordhorn & Grafschaft Bentheim, Nedersaksen"
                invoer.equals("NOL") -> resultaat.text = "Niederschlesischer Oberlausitzkreis, Saksen"
                invoer.equals("NOM") -> resultaat.text = "Northeim, Nedersaksen"
                invoer.equals("NOR") -> resultaat.text = "Norden, Nedersaksen"
                invoer.equals("NP") -> resultaat.text = "Neuruppin, Brandenburg"
                invoer.equals("NR") -> resultaat.text = "Neuwied am Rhein, Rijnland-Palts"
                invoer.equals("NRÜ") -> resultaat.text = "Neustadt am Rübenberge, Nedersaksen"
                invoer.equals("NRW") -> resultaat.text = "Nordrijn-Westfalen (staats)voertuigen"
                invoer.equals("NU") -> resultaat.text = "Neu-Ulm, Beieren"
                invoer.equals("NT") -> resultaat.text = "Nürtingen, Baden-Württemberg"
                invoer.equals("NVP") -> resultaat.text = "Nordvorpommern, Mecklenburg-Voor-Pommeren" 
                invoer.equals("NW") -> resultaat.text = "Neustadt an der Weinstraße, Rijnland-Palts"
                invoer.equals("NWM") -> resultaat.text = "Nordwestmecklenburg, Mecklenburg-Voor-Pommeren" 
                invoer.equals("NY") -> resultaat.text = "Niesky, Saksen"
                invoer.equals("NZ") -> resultaat.text = "Neustrelitz, Mecklenburg-Voor-Pommeren" 

                //O
                invoer.equals("OA") -> resultaat.text = "Oberallgäu, Beieren"
                invoer.equals("OAL") -> resultaat.text = "Ostallgäu, Beieren"
                invoer.equals("OB") -> resultaat.text = "Oberhausen, Noordrijn-Westfalen" 
                invoer.equals("OBB") -> resultaat.text = "Obernburg, Beieren"
                invoer.equals("OBG") -> resultaat.text = "Osterburg, Saksen-Anhalt"
                invoer.equals("OC") -> resultaat.text = "Oschersleben, Saksen"
                invoer.equals("OCH") -> resultaat.text = "Ochsenfurt, Beieren"
                invoer.equals("OD") -> resultaat.text = "Bad Aldesloe & Stormarn, Sleeswijk-Holstein"
                invoer.equals("OE") -> resultaat.text = "Olpe, Noordrijn-Westfalen" 
                invoer.equals("OF") -> resultaat.text = "Offenbach am Main, Hessen"
                invoer.equals("OG") -> resultaat.text = "Offenburg & Ortenaukreis, Baden"
                invoer.equals("OH") -> resultaat.text = "Ostholstein, Sleeswijk-Holstein"
                invoer.equals("OHA") -> resultaat.text = "Osterode am Harz, Nedersaksen"
                invoer.equals("ÖHR") -> resultaat.text = "Öhringen, Baden-Württemberg"
                invoer.equals("OHV") -> resultaat.text = "Oberhavel, Brandenburg"
                invoer.equals("OHZ") -> resultaat.text = "Osterholz, Nedersaksen"
                invoer.equals("OK") -> resultaat.text = "Ohre-Kreis, Nedersaksen"
                invoer.equals("OL") -> resultaat.text = "Oldenburg, Nedersaksen"
                invoer.equals("OLD") -> resultaat.text = "Oldenburg (Holstein), Sleeswijk-Holstein"
                invoer.equals("OP") -> resultaat.text = "Opladen, Noordrijn-Westfalen" 
                invoer.equals("OPR") -> resultaat.text = "Ostprignitz-Ruppin, Brandenburg"
                invoer.equals("OR") -> resultaat.text = "Oranienburg, Brandenburg"
                invoer.equals("OS") -> resultaat.text = "Osnabrück, Nedersaksen"
                invoer.equals("OSL") -> resultaat.text = "Oberspreewald-Sausitz, Brandenburg"
                invoer.equals("OTT") -> resultaat.text = "Ottendorf, Nedersaksen"
                invoer.equals("OTW") -> resultaat.text = "Ottweiler, Saarland"
                invoer.equals("OVI") -> resultaat.text = "Oberviechtach, Beieren"
                invoer.equals("OVL") -> resultaat.text = "Obervogtland, Saksen"
                invoer.equals("OVP") -> resultaat.text = "Ostvorpommern, Mecklenburg-Voor-Pommeren" 
                invoer.equals("OZ") -> resultaat.text = "Oschatz, Saksen"

                //P
                invoer.equals("P") -> resultaat.text = "Potsdam, Brandenburg"
                invoer.equals("PA") -> resultaat.text = "Passau, Beieren"
                invoer.equals("PAF") -> resultaat.text = "Pfaffenhofen an der Ilm, Beieren"
                invoer.equals("PAN") -> resultaat.text = "Pfarrkirchen & Rottal-Inn, Beieren"
                invoer.equals("PAR") -> resultaat.text = "Parsberg, Beieren"
                invoer.equals("PB") -> resultaat.text = "Paderborn, Noordrijn-Westfalen" 
                invoer.equals("PCH") -> resultaat.text = "Parchim, Mecklenburg-Voor-Pommeren" 
                invoer.equals("PE") -> resultaat.text = "Peiene, Nedersaksen"
                invoer.equals("PEG") -> resultaat.text = "Pegnitz, Beieren"
                invoer.equals("PF") -> resultaat.text = "Pforzheim & Enzkreis, Baden"
                invoer.equals("PI") -> resultaat.text = "Pinneberg, Sleeswijk-Holstein"
                invoer.equals("PIR") -> resultaat.text = "Sächsische Schweiz (Pirna), Saksen"
                invoer.equals("PK") -> resultaat.text = "Pritzwalk, Brandenburg"
                invoer.equals("PL") -> resultaat.text = "Plauen, Saksen"
                invoer.equals("PLÖ") -> resultaat.text = "Plön, Sleeswijk-Holstein"
                invoer.equals("PM") -> resultaat.text = "Potsdam-Mittelmark, Brandenburg"
                invoer.equals("PN") -> resultaat.text = "Pößneck, Thüringen" 
                invoer.equals("PR") -> resultaat.text = "Prignitz, Brandenburg"
                invoer.equals("PRÜ") -> resultaat.text = "Prüm, Rijnland-Palts"
                invoer.equals("PS") -> resultaat.text = "Pirmasens & Südwestpfalz, Rijnland-Palts"
                invoer.equals("PW") -> resultaat.text = "Pasewalk, Mecklenburg-Voor-Pommeren" 
                invoer.equals("PZ") -> resultaat.text = "Prenzlau, Brandenbung"

                //Q
                invoer.equals("Q") -> resultaat.text = "Querfurt, Saksen-Anhalt"
                invoer.equals("QLB") -> resultaat.text = "Quedlinburg, Saksen-Anhalt"

                //R
                invoer.equals("R") -> resultaat.text = "Regensburg, Beieren"
                invoer.equals("RA") -> resultaat.text = "Ratstatt, Baden"
                invoer.equals("RC") -> resultaat.text = "Reichenbach, Saksen"
                invoer.equals("RD") -> resultaat.text = "Rendsburg-Eckernförde, Sleeswijk-Holstein"
                invoer.equals("RDG") -> resultaat.text = "Ribnitz-Damgarten, Mecklenburg-Voor-Pommeren" 
                invoer.equals("RE") -> resultaat.text = "Recklingenhausen, Noordrijn-Westfalen" 
                invoer.equals("REG") -> resultaat.text = "Regen, Beieren"
                invoer.equals("REH") -> resultaat.text = "Rehau, Beieren"
                invoer.equals("REI") -> resultaat.text = "Bad Reichenhal, Beieren"
                invoer.equals("RG") -> resultaat.text = "Riesa-Großenhain, Saksen"
                invoer.equals("RH") -> resultaat.text = "Roth bei Nürnberg, Beieren"
                invoer.equals("RI") -> resultaat.text = "Rinteln, Nedensaksen"
                invoer.equals("RID") -> resultaat.text = "Riedenburg, Beieren"
                invoer.equals("RIE") -> resultaat.text = "Riesa, Saksen"
                invoer.equals("RL") -> resultaat.text = "Rochlitz, Saksen"
                invoer.equals("RM") -> resultaat.text = "Röbel/Muritz, Mecklenburg-Voor-Pommeren" 
                invoer.equals("RN") -> resultaat.text = "Rathenow, Brandenburg"
                invoer.equals("RO") -> resultaat.text = "Rosenheim, Beieren"
                invoer.equals("ROD") -> resultaat.text = "Roding, Beieren"
                invoer.equals("ROF") -> resultaat.text = "Rotenburg bei Fulda, Hessen"
                invoer.equals("ROH") -> resultaat.text = "Rotenburg Wümme, Nedersaksen"
                invoer.equals("ROK") -> resultaat.text = "Rokcenhausen, Rijnland Palts"
                invoer.equals("ROL") -> resultaat.text = "Rottenburg Laaber, Beieren"
                invoer.equals("ROS") -> resultaat.text = "Rostock Land, Mecklenburg-Voor-Pommeren" 
                invoer.equals("ROT") -> resultaat.text = "Rothenburg ob der Tauber, Beieren"
                invoer.equals("ROW") -> resultaat.text = "Rotenburg (Wümme) & Bremervörde, Nedersaksen"
                invoer.equals("RPL") -> resultaat.text = "Rijnland-Palts (staats)voertuigen"
                invoer.equals("RS") -> resultaat.text = "Remscheid, Noordrijn-Westfalen" 
                invoer.equals("RSL") -> resultaat.text = "Roßlau, Saksen-Anhalt"
                invoer.equals("RT") -> resultaat.text = "Reutlingen, Baden"
                invoer.equals("RU") -> resultaat.text = "Rudolstadt"
                invoer.equals("RÜD") -> resultaat.text = "Rüdesheim & Rheingau-Taunus-Kreis, Hessen"
                invoer.equals("RÜG") -> resultaat.text = "Rügen, Mecklenburg-Voor-Pommeren" 
                invoer.equals("RV") -> resultaat.text = "Ravensubrg, Baden"
                invoer.equals("RW") -> resultaat.text = "Rottweil, Baden"
                invoer.equals("RWL") -> resultaat.text = "Noordrijn-Westfalen (staats)voertuigen"
                invoer.equals("RY") -> resultaat.text = "Rheydt, Noordrijn-Westfalen" 
                invoer.equals("RZ") -> resultaat.text = "Ratzeburg & Hertzogtum Lauenburg, Sleeswijk-Holstein"

                //S
                invoer.equals("S") -> resultaat.text = "Stuttgart, Baden"
                invoer.equals("SAB") -> resultaat.text = "Saarburg, Rijnland-Palts"
                invoer.equals("SAD") -> resultaat.text = "Schwandorf, Beieren"
                invoer.equals("SÄK") -> resultaat.text = "Säckingen, Baden"
                invoer.equals("SAL") -> resultaat.text = "Saarland (Staats)voertuigen"
                invoer.equals("SAN") -> resultaat.text = "Stadtsteinach, Beieren"
                invoer.equals("SAO") -> resultaat.text = "Saale-Orla Kreis"
                invoer.equals("SAW") -> resultaat.text = "Altmarkkreis Salzwedel, Saksen-Anhalt"
                invoer.equals("SB") -> resultaat.text = "Saarbrücken, Saarland"
                invoer.equals("SBG") -> resultaat.text = "Strasburg, Mecklenburg-Voor-Pommeren" 
                invoer.equals("SBK") -> resultaat.text = "Schönebeck, Saksen-Anhalt"
                invoer.equals("SC") -> resultaat.text = "Schwabach, Beieren"
                invoer.equals("SCZ") -> resultaat.text = "Schleiz, Thüringen" 
                invoer.equals("SDH") -> resultaat.text = "Sondershausen, Thüringen" 
                invoer.equals("SDL") -> resultaat.text = "Stendal, Saksen-Anhalt"
                invoer.equals("SDT") -> resultaat.text = "Schwedt, Brandenburg"
                invoer.equals("SE") -> resultaat.text = "Segeberg, Sleeswijk-Holstein"
                invoer.equals("SEB") -> resultaat.text = "Sebnitz, Saksen"
                invoer.equals("SEE") -> resultaat.text = "Seelow, Brandenburg"
                invoer.equals("SEF") -> resultaat.text = "Scheinfeld, Beieren"
                invoer.equals("SEL") -> resultaat.text = "Selb, Beieren"
                invoer.equals("SF") -> resultaat.text = "Sonthofen, Beieren"
                invoer.equals("SFA") -> resultaat.text = "Soltau-Falingbostel, Nedersaksen"
                invoer.equals("SFB") -> resultaat.text = "Senftenberg, Brandenburg"
                invoer.equals("SFT") -> resultaat.text = "Staßfurt, Saksen-Anhalt"
                invoer.equals("SG") -> resultaat.text = "Solingen, Noordrijn-Westfalen" 
                invoer.equals("SGH") -> resultaat.text = "Sangerhausen, Saksen-Anhalt"
                invoer.equals("SH") -> resultaat.text = "Sleeswijk-Holstein (staats)voertuigen"
                invoer.equals("SHA") -> resultaat.text = "Schwäbisch Hall, Baden-Württemberg"
                invoer.equals("SHG") -> resultaat.text = "Stadthagen & Schaumberg, Nedersaksen"
                invoer.equals("SHK") -> resultaat.text = "Saale-Holzland-Kreis, Thüringen" 
                invoer.equals("SHL") -> resultaat.text = "Suhl, Thüringen" 
                invoer.equals("SI") -> resultaat.text = "Siegen-Wittgenstein, Noordrijn-Westfalen" 
                invoer.equals("SIG") -> resultaat.text = "Sigmaringen, Baden"
                invoer.equals("SIM") -> resultaat.text = "Simmern & Rhein-Hunsrück-Kreis, Rijnland-Palts"
                invoer.equals("SK") -> resultaat.text = "Saalkreis, Saksen-Anhalt"
                invoer.equals("SL") -> resultaat.text = "Schleswig-Flensburg, Sleeswijk-Holstein"
                invoer.equals("SLE") -> resultaat.text = "Schleiden (Eifel), Noordrijn-Westfalen" 
                invoer.equals("SLF") -> resultaat.text = "Saalfeld-Rudolstadt, Thüringen" 
                invoer.equals("SLG") -> resultaat.text = "Saalgau, Baden"
                invoer.equals("SLK") -> resultaat.text = "Salzlandkreis, Saksen-Anhalt"
                invoer.equals("SLN") -> resultaat.text = "Schmölin, Thüringen" 
                invoer.equals("SLS") -> resultaat.text = "Saarlouis, Saarland"
                invoer.equals("SLÜ") -> resultaat.text = "Schlüchtern, Hessen"
                invoer.equals("SLZ") -> resultaat.text = "Bad Salzungen, Thüringen" 
                invoer.equals("SM") -> resultaat.text = "Schmalkalden-Meingingen, Thüringen" 
                invoer.equals("SMÜ") -> resultaat.text = "Schwabmünchen, Beieren"
                invoer.equals("SN") -> resultaat.text = "Schwerin, Mecklenburg-Voor-Pommeren" 
                invoer.equals("SNH") -> resultaat.text = "Sinsheim, Baden"
                invoer.equals("SO") -> resultaat.text = "Soest, Noordrijn-Westfalen" 
                invoer.equals("SOB") -> resultaat.text = "Schrobenhausen, Beieren"
                invoer.equals("SOG") -> resultaat.text = "Schongau, Beieren"
                invoer.equals("SOK") -> resultaat.text = "Saale-Orla-Kreis, Thüringen" 
                invoer.equals("SOL") -> resultaat.text = "Soltau, Nedersaksen"
                invoer.equals("SÖM") -> resultaat.text = "Sömmerda, Thüringen" 
                invoer.equals("SON") -> resultaat.text = "Sonneberg, Thüringen" 
                invoer.equals("SP") -> resultaat.text = "Speyer, Rijnland-Palts"
                invoer.equals("SPB") -> resultaat.text = "Spremberg, Brandenburg"
                invoer.equals("SPN") -> resultaat.text = "Spree-Neiße, Brandenburg"
                invoer.equals("SPR") -> resultaat.text = "Springe, Nedersaksen"
                invoer.equals("SR") -> resultaat.text = "Straubing & Straubingen-Bogen, Beieren"
                invoer.equals("SRB") -> resultaat.text = "Strausberg, Brandenberg"
                invoer.equals("SRO") -> resultaat.text = "Stadtroda, Thüringen" 
                invoer.equals("ST") -> resultaat.text = "Steinfurt, Noordrijn-Westfalen" 
                invoer.equals("STA") -> resultaat.text = "Starnberg, Beieren"
                invoer.equals("STB") -> resultaat.text = "Sternberg, Mecklenburg-Voor-Pommeren" 
                invoer.equals("STD") -> resultaat.text = "Stade, Nedersaksen"
                invoer.equals("STE") -> resultaat.text = "Staffelstein, Beieren"
                invoer.equals("STH") -> resultaat.text = "Stadthagen, Nedersaksen"
                invoer.equals("STL") -> resultaat.text = "Stollberg, Saksen"
                invoer.equals("STO") -> resultaat.text = "Stockach, Baden"
                invoer.equals("SU") -> resultaat.text = "Siegburg & Rhein-Sieg-Kreis, Noordrijn-Westfalen" 
                invoer.equals("SUL") -> resultaat.text = "Sulzbach-Rosenberg, Beieren"
                invoer.equals("SÜW") -> resultaat.text = "Südliche Weinstraße, Rijnland-Palts"
                invoer.equals("SW") -> resultaat.text = "Schweinfurt, Beieren"
                invoer.equals("SWA") -> resultaat.text = "Bad Schwalbach & Rheingau-Taunus-Kreis, Hessen"
                invoer.equals("SWZ") -> resultaat.text = "Schwarzakreis"
                invoer.equals("SY") -> resultaat.text = "Syke, Nedersaksen"
                invoer.equals("SZ") -> resultaat.text = "Salzgitter, Nedersaksen"
                invoer.equals("SZB") -> resultaat.text = "Schwarzenberg, Saksen"

                //T
                invoer.equals("TBB") -> resultaat.text = "Tauberbeschofsheim & Main-Tauber-Kreis, Baden"
                invoer.equals("TE") -> resultaat.text = "Teterow, Mecklenburg-Voor-Pommeren" 
                invoer.equals("TF") -> resultaat.text = "Teltow-Fläming, Brandenburg"
                invoer.equals("TG") -> resultaat.text = "Torgau, Saksen"
                invoer.equals("THL") -> resultaat.text = "Thüringen (staats)voertuigen"
                invoer.equals("TIR") -> resultaat.text = "Tirschenreuth, Beieren"
                invoer.equals("TO") -> resultaat.text = "Torgau-Oschatz, Saksen"
                invoer.equals("TÖL") -> resultaat.text = "Bad Tölz-Wolfratshausen, Beieren"
                invoer.equals("TÖN") -> resultaat.text = "Tönning, Sleeswijk-Holstein"
                invoer.equals("TP") -> resultaat.text = "Templin, Brandenburg"
                invoer.equals("TR") -> resultaat.text = "Trier, Rijnland-Palts"
                invoer.equals("TS") -> resultaat.text = "Traunstein, Beieren"
                invoer.equals("TT") -> resultaat.text = "Tettnang, Baden"
                invoer.equals("TÜ") -> resultaat.text = "Tübingen, Baden"
                invoer.equals("TUT") -> resultaat.text = "Tuttlingen, Baden"

                //U
                invoer.equals("ÜB") -> resultaat.text = "Überlingen, Baden"
                invoer.equals("UE") -> resultaat.text = "Eulzen, Nedersaksen"
                invoer.equals("UEM") -> resultaat.text = "Ueckermünde, Mecklenburg-Voor-Pommeren" 
                invoer.equals("UER") -> resultaat.text = "Uecker-Randow, Mecklenburg-Voor-Pommeren" 
                invoer.equals("UFF") -> resultaat.text = "Uffenheim, Beieren"
                invoer.equals("UH") -> resultaat.text = "Utstrut-Hainich, Thüringen" 
                invoer.equals("UL") -> resultaat.text = "Ulm & Alb-Donau-Kreis, Baden"
                invoer.equals("UM") -> resultaat.text = "Uckermark, Brandenburg"
                invoer.equals("UN") -> resultaat.text = "Unna, Noordrijn-Westfalen" 
                invoer.equals("USI") -> resultaat.text = "Usingen, Hessen"

                //V
                invoer.equals("V") -> resultaat.text = "Vogtlandkreis, Saksen"
                invoer.equals("VAI") -> resultaat.text = "Vaihingen, Baden"
                invoer.equals("VB") -> resultaat.text = "Vogelsbergkreis, Hessen"
                invoer.equals("VEC") -> resultaat.text = "Vechta, Nedersaksen"
                invoer.equals("VER") -> resultaat.text = "Verden, Nedersaksen"
                invoer.equals("VIB") -> resultaat.text = "Vilsbiburg, Beieren"
                invoer.equals("VIE") -> resultaat.text = "Viersen, Noordrijn-Westfalen" 
                invoer.equals("VIT") -> resultaat.text = "Viechtach, Beieren"
                invoer.equals("VK") -> resultaat.text = "Völklingen, Saarland"
                invoer.equals("VL") -> resultaat.text = "Villingen, Baden"
                invoer.equals("VOF") -> resultaat.text = "Vilshofen, Beieren"
                invoer.equals("VOH") -> resultaat.text = "Vohenstrauß, Beieren"
                invoer.equals("VR") -> resultaat.text = "Vorpommern-Rügen, Mecklenburg-Voor-Pommeren" 
                invoer.equals("VS") -> resultaat.text = "Villingen-Schwenningen & Schwarzwald-Baar-Kreis, Baden"

                //W
                invoer.equals("W") -> resultaat.text = "Wuppertal, Noordrijn-Westfalen" 
                invoer.equals("WA") -> resultaat.text = "Waldeck, Hessen"
                invoer.equals("WAF") -> resultaat.text = "Kreis Warendorf, Noordrijn-Westfalen" 
                invoer.equals("WAK") -> resultaat.text = "Wartburgkreis, Thüringen" 
                invoer.equals("WAM") -> resultaat.text = "Westliche Altmark"
                invoer.equals("WAN") -> resultaat.text = "Wanne-Eickel, Noordrijn-Westfalen" 
                invoer.equals("WAR") -> resultaat.text = "Warburg, Noordrijn-Westfalen" 
                invoer.equals("WAT") -> resultaat.text = "Wattenscheid, Noordrijn-Westfalen" 
                invoer.equals("WB") -> resultaat.text = "Wittenberg, Saksen-Anhalt"
                invoer.equals("WBS") -> resultaat.text = "Worbis, Thüringen" 
                invoer.equals("WD") -> resultaat.text = "Weidenbrück, Noordrijn-Westfalen" 
                invoer.equals("WDA") -> resultaat.text = "Werdau, Saksen"
                invoer.equals("WE") -> resultaat.text = "Weimar, Thüringen" 
                invoer.equals("WEB") -> resultaat.text = "Westerburg, Rijnland-Palts"
                invoer.equals("WEG") -> resultaat.text = "Wegscheid, Beieren"
                invoer.equals("WEL") -> resultaat.text = "Weilburg, Hessen"
                invoer.equals("WEM") -> resultaat.text = "Wesermünde, Nedersaksen"
                invoer.equals("WEN") -> resultaat.text = "Weiden in der Oberpfalz, Beieren"
                invoer.equals("WER") -> resultaat.text = "Wertingen, Beieren"
                invoer.equals("WES") -> resultaat.text = "Wesel, Noordrijn-Westfalen" 
                invoer.equals("WF") -> resultaat.text = "Wolfenbüttel, Nedersaksen"
                invoer.equals("WG") -> resultaat.text = "Wangen, Baden"
                invoer.equals("WHV") -> resultaat.text = "Wilhelmshaven, Nedersaksen"
                invoer.equals("WI") -> resultaat.text = "Wiesbaden, Hessen"
                invoer.equals("WIL") -> resultaat.text = "Wittlich & Bernkastel-Wittlich, Rijnland-Palts"
                invoer.equals("WIS") -> resultaat.text = "Landkreis Nordwestmecklenburg (Wismar), Mecklenburg-Voor-Pommeren" 
                invoer.equals("WIT") -> resultaat.text = "Witten, Noordrijn-Westfalen" 
                invoer.equals("WIZ") -> resultaat.text = "Witzenhausen, Hessen"
                invoer.equals("WK") -> resultaat.text = "Wittstock, Brandenburg"
                invoer.equals("WL") -> resultaat.text = "Winsen (Luhe) & Harburg, Nedersaksen"
                invoer.equals("WLG") -> resultaat.text = "Wolgast, Mecklenburg-Voor-Pommeren" 
                invoer.equals("WM") -> resultaat.text = "Weilheim-Schongau, Beieren"
                invoer.equals("WMS") -> resultaat.text = "Wolmirstedt, Saksen-Anhalt"
                invoer.equals("WN") -> resultaat.text = "Waiblingen & Rems-Murr-Kreis, Baden"
                invoer.equals("WND") -> resultaat.text = "St Wendel, Saarland"
                invoer.equals("WO") -> resultaat.text = "Worms, Rijnland-Palts"
                invoer.equals("WOB") -> resultaat.text = "Wolfsburg, Nedersaksen"
                invoer.equals("WOH") -> resultaat.text = "Wolfhagen, Hessen"
                invoer.equals("WOL") -> resultaat.text = "Wolfach, Baden"
                invoer.equals("WOR") -> resultaat.text = "Wolfratshausen, Beieren"
                invoer.equals("WOS") -> resultaat.text = "Wolfstein, Beieren"
                invoer.equals("WR") -> resultaat.text = "Wernigerode, Saksen-Anhalt"
                invoer.equals("WRN") -> resultaat.text = "Waren, Mecklenburg-Voor-Pommeren" 
                invoer.equals("WS") -> resultaat.text = "Wasserburg, Beieren"
                invoer.equals("WSF") -> resultaat.text = "Weißenfels, Saksen-Anhalt"
                invoer.equals("WST") -> resultaat.text = "Westerstede & Ammerland, Nedersaksen"
                invoer.equals("WSW") -> resultaat.text = "Weißwasser, Saksen"
                invoer.equals("WT") -> resultaat.text = "Waldshut, Baden"
                invoer.equals("WTM") -> resultaat.text = "Wittmund, Nedersaksen"
                invoer.equals("WÜ") -> resultaat.text = "Würzburg, Beieren"
                invoer.equals("WUG") -> resultaat.text = "Weißenburg-Gunzenhausen, Beieren"
                invoer.equals("WUM") -> resultaat.text = "Waldmünchen, Beieren"
                invoer.equals("WUN") -> resultaat.text = "Wunsiedel am Fichtelgerbirge, Beieren"
                invoer.equals("WUR") -> resultaat.text = "Wurzen, Saksen"
                invoer.equals("WW") -> resultaat.text = "Westerwaldkreis, Rijnland-Palts"
                invoer.equals("WZ") -> resultaat.text = "Wetzlar, Hessen"
                invoer.equals("WZL") -> resultaat.text = "Wanzleben, Saksen-Anhalt"

                //Z
                invoer.equals("Z") -> resultaat.text = "Zwickauer Land, Saksen"
                invoer.equals("ZE") -> resultaat.text = "Zerbst, Saksen-Anhalt"
                invoer.equals("ZEL") -> resultaat.text = "Zell, Rijnland-Palts"
                invoer.equals("ZI") -> resultaat.text = "Löbau-Zittau, Saksen"
                invoer.equals("ZIG") -> resultaat.text = "Ziegenhain, Hessen"
                invoer.equals("ZP") -> resultaat.text = "Zschopau, Saksen"
                invoer.equals("ZR") -> resultaat.text = "Zeulenroda, Thüringen" 
                invoer.equals("ZS") -> resultaat.text = "Zossen, Brandenburg"
                invoer.equals("ZW") -> resultaat.text = "Zweibrücken, Rijnland-Palts"
                invoer.equals("ZZ") -> resultaat.text = "Zeitz, Saksen-Anhalt"


                else -> resultaat.text = "je hebt iets verkeerd getypt!"
            }
        }
    }
}

//voor copy pasta: invoer.equals("Z") -> resultaat.text = ""
